"""Data fields updated

Revision ID: e09e45dfd374
Revises: 002777235231
Create Date: 2025-08-19 19:56:40.258433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09e45dfd374'
down_revision: Union[str, Sequence[str], None] = '002777235231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('metadata_', sa.JSON(), nullable=True))
    op.add_column('data', sa.Column('has_been_indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'has_been_indexed')
    op.drop_column('data', 'metadata_')
    # ### end Alembic commands ###
